type Vehicle = {
    id: string;
    make: string;
};

export const VEHICLE_MAKES: Vehicle[] = [
    { id: "1", make: "Acura" },
    { id: "2", make: "Alfa Romeo" },
    { id: "3", make: "Aston Martin" },
    { id: "4", make: "Audi" },
    { id: "5", make: "Bentley" },
    { id: "6", make: "BMW" },
    { id: "7", make: "Buick" },
    { id: "8", make: "BYD" },
    { id: "9", make: "Changan" },
    { id: "10", make: "Chevrolet" },
    { id: "11", make: "Chrysler" },
    { id: "12", make: "Citroën" },
    { id: "13", make: "Daihatsu" },
    { id: "14", make: "Daewoo" },
    { id: "15", make: "Dodge" },
    { id: "16", make: "Ferrari" },
    { id: "17", make: "Fiat" },
    { id: "18", make: "Ford" },
    { id: "19", make: "Genesis" },
    { id: "20", make: "Geely" },
    { id: "21", make: "GMC" },
    { id: "22", make: "Great Wall" },
    { id: "23", make: "Holden" },
    { id: "24", make: "Honda" },
    { id: "25", make: "Hummer" },
    { id: "26", make: "Hyundai" },
    { id: "27", make: "Infiniti" },
    { id: "28", make: "Jaguar" },
    { id: "29", make: "Jeep" },
    { id: "30", make: "Kia" },
    { id: "31", make: "Koenigsegg" },
    { id: "32", make: "Lamborghini" },
    { id: "33", make: "Lancia" },
    { id: "34", make: "Land Rover" },
    { id: "35", make: "Lexus" },
    { id: "36", make: "Lotus" },
    { id: "37", make: "Lucid" },
    { id: "38", make: "Mahindra" },
    { id: "39", make: "Mazda" },
    { id: "40", make: "McLaren" },
    { id: "41", make: "Mercedes-Benz" },
    { id: "42", make: "Mini" },
    { id: "43", make: "Mitsubishi" },
    { id: "44", make: "Nissan" },
    { id: "45", make: "Oldsmobile" },
    { id: "46", make: "Pagani" },
    { id: "47", make: "Peugeot" },
    { id: "48", make: "Perodua" },
    { id: "49", make: "Pontiac" },
    { id: "50", make: "Porsche" },
    { id: "51", make: "Proton" },
    { id: "52", make: "Ram" },
    { id: "53", make: "Renault" },
    { id: "54", make: "Rivian" },
    { id: "55", make: "Rolls-Royce" },
    { id: "56", make: "Saab" },
    { id: "57", make: "Saturn" },
    { id: "58", make: "Scion" },
    { id: "59", make: "Seat" },
    { id: "60", make: "Skoda" },
    { id: "61", make: "Smart" },
    { id: "62", make: "Subaru" },
    { id: "63", make: "Suzuki" },
    { id: "64", make: "Tata" },
    { id: "65", make: "Tesla" },
    { id: "66", make: "Toyota" },
    { id: "67", make: "Volkswagen" },
    { id: "68", make: "Volvo" },
];
